### PR TITLE
Remove configuration parameters object

### LINKED ISSUE #95: 401 Unauthorized Error while renewing session
While re-authentication of a device, server always returns 401.

I believe this is because of an old bearerToken which is not cleared during the server authentication request.

_I will try to open a pull request._ : failed, because I couldn't manage to run the tests.  I will not open a pull request.

to reproduce:
Create a short session using client.authenticateDevice(id);
wait until it expires.
try to create another session using client.authenticateDevice(id);

Error message:
`{"type":"default","status":401,"ok":false,"statusText":"","headers":{"map":{"content-encoding":"gzip","cache-control":"no-store, no-cache, must-revalidate","content-length":"66","content-type":"application/json","vary":"Accept-Encoding","date":"Mon, 24 May 2021 22:40:02 GMT"}},"url":"http://127.0.0.1:7350/v2/account/authenticate/device?","bodyUsed":false,"_bodyInit":{"_data":{"size":42,"offset":0,"blobId":"95393CD0-52C6-41B2-A924-19B810B1FA20","type":"application/json","name":"device","__collector":{}}},"_bodyBlob":{"_data":{"size":42,"offset":0,"blobId":"95393CD0-52C6-41B2-A924-19B810B1FA20","type":"application/json","name":"device","__collector":{}}}}`

### PR DESCRIPTION
**Pull request by lugehorsam**
- Fixes #95 
- Refactors the code for passing bearer token and basic auth creds to the api client. Rather than setting them on a stateful object we just pass them as parameters. This is what nakama-dotnet does.
- Renamed `rpcGet` to `rpcHttpKey` and removed the session param since it took an http key and an input object anyway.

### CODE REVIEW

File: packages/nakama-js/utils.ts [hunk 1]
```diff
@@ -1,5 +1,57 @@
 import {encode, decode} from "js-base64"
 
+export function buildFullUrl(basePath: string, fragment: string, queryParams: Map<string, any>)
```
Comment (novabyte) [inline packages/nakama-js/utils.ts:3]: I think we should inline these functions as part of the output of the codegen tool so that the tool's output is always standalone. This makes it easier to fulfil one of our later goals to consolidate our codegen utils under a single repo as an official CLI.

**Review by novabyte — COMMENTED** [review]
@lugehorsam Small comment otherwise all looks good to me 👍
